### ISSUE TITLE
Azure Functions Core tools

### ISSUE THREAD

**Issue by Scherlac** [rljacobson/OptOutEnv#3]
Telemetry
---------
The Azure Functions Core tools collect usage data in order to help us improve your experience.
The data is anonymous and doesn't include any user specific or personal information. The data is collected by Microsoft.

You can opt-out of telemetry by setting the FUNCTIONS_CORE_TOOLS_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

URL: https://github.com/Azure/azure-functions-core-tools#telemetry

**Comment by rljacobson** [comment]
Thanks. I think [toptout](https://github.com/beatcracker/toptout) is so much better at accomplishing the goals of this repo that I should freeze this one and just point to toptout. It looks like they have this one on the slate to be added.
